### ISSUE TITLE
Neon as generative NFT

### ISSUE THREAD

**Issue by Archethect** [Stanko/neon#13]
Hello Stanko,

I love your Neon generative art you have made. Really really cool.
Myself, I am a solidity developer specializing in NFTs on Ethereum. I think this work would be perfect for a generative art project as NFTs. I shared your work in the community and had some positive feedback. 
Would you mind if I create generative NFTs based on your work? 

Kind regards,

Archethect

**Comment by Stanko** [comment]
Hello @Archethect,
Thank you for the kind words, I'm glad you like Neon! 

Honestly, I would prefer for Neon to stay as it is, completely open source, and with no NFTs involved. Sorry about that.

Cheers!

**Comment by Archethect** [comment]
Hey Stanko.

I respect your stance and will not create NFTs of it! Should you ever reconsider, let me know. I can do some Solidity development.

Kind regards,

Archethect.
